//! The Autocorrect list: Bengali words as the engine spells them when a vowel
//! between two consonants was left out, mapped to their correct spelling
//! (`আম্রা` → `আমরা`, autocorrect design D2).
//!
//! The engine never reads it, so typing stays a function of the keys alone.
//! The composer applies it to a word when the word ends, and bulk conversion
//! to every word of its output, only when [`Config::autocorrect`] is on.
//!
//! The list is generated by `scripts/autocorrect/generate.py` (design D3) and
//! embedded at build time. It is licensed CC BY-SA 4.0 (`data/LICENSE-DATA`,
//! design D7).
//!
//! [`Config::autocorrect`]: crate::Config::autocorrect

use std::borrow::Cow;
use std::sync::OnceLock;

use crate::letters::is_word_char;

/// The generated list: `engine<TAB>correct<TAB>roman` per line, sorted by
/// the engine spelling, after `#` comment lines.
const LIST: &str = include_str!("../data/autocorrect.tsv");

/// Decomposed nukta letters and their precomposed forms. The engine writes
/// the precomposed ones, and so does the list.
const NUKTA_LETTERS: [(&str, &str); 3] = [
    ("\u{09A1}\u{09BC}", "\u{09DC}"), // ড়
    ("\u{09A2}\u{09BC}", "\u{09DD}"), // ঢ়
    ("\u{09AF}\u{09BC}", "\u{09DF}"), // য়
];

/// One line of the list.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Entry {
    /// What the engine gives for the roman spelling as typed.
    engine: &'static str,
    /// What it gives with `o` typed at each `_`: the engine spelling minus
    /// one or more hasants.
    correct: &'static str,
    /// The roman spelling, with `_` where the vowel was left out.
    roman: &'static str,
}

/// The parsed list, sorted by [`Entry::engine`] for binary search.
fn entries() -> &'static [Entry] {
    static ENTRIES: OnceLock<Vec<Entry>> = OnceLock::new();
    ENTRIES.get_or_init(|| {
        let entries: Vec<Entry> = LIST
            .lines()
            .filter(|line| !line.is_empty() && !line.starts_with('#'))
            .filter_map(|line| {
                let mut fields = line.split('\t');
                let entry = Entry {
                    engine: fields.next()?,
                    correct: fields.next()?,
                    roman: fields.next()?,
                };
                debug_assert!(fields.next().is_none(), "extra field in {line:?}");
                Some(entry)
            })
            .collect();
        // The generator sorts the file; the tests check it.
        debug_assert!(entries.windows(2).all(|w| w[0].engine < w[1].engine));
        entries
    })
}

/// `word` with any decomposed nukta letter precomposed.
fn precompose_nukta(word: &str) -> Cow<'_, str> {
    if !word.contains('\u{09BC}') {
        return Cow::Borrowed(word);
    }
    let mut word = word.to_owned();
    for (decomposed, composed) in NUKTA_LETTERS {
        word = word.replace(decomposed, composed);
    }
    Cow::Owned(word)
}

/// The correct spelling of `word`, when the list has it (autocorrect spec,
/// "Lookup by engine output"). `word` is one whole Bengali word as the engine
/// wrote it; any other word gives `None`.
pub(crate) fn lookup(word: &str) -> Option<&'static str> {
    let word = precompose_nukta(word);
    let entries = entries();
    entries
        .binary_search_by(|entry| entry.engine.cmp(&word))
        .ok()
        .map(|index| entries[index].correct)
}

/// `text` with every Bengali word in the list corrected (autocorrect spec,
/// "Autocorrect in bulk conversion"). Words are the runs the composer keeps
/// pending; everything between them is copied as is.
pub(crate) fn correct_words(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while !rest.is_empty() {
        let word_len = rest.find(|c: char| !is_word_char(c)).unwrap_or(rest.len());
        let (word, after) = rest.split_at(word_len);
        out.push_str(lookup(word).unwrap_or(word));
        let gap_len = after.find(is_word_char).unwrap_or(after.len());
        out.push_str(&after[..gap_len]);
        rest = &after[gap_len..];
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transpile_roman_document;

    const HASANT: char = '\u{09CD}';

    /// Whether removing one or more hasants from `engine`, and nothing else,
    /// gives `correct`.
    fn only_hasants_removed(engine: &str, correct: &str) -> bool {
        let mut correct_chars = correct.chars().peekable();
        let mut removed = 0;
        for c in engine.chars() {
            if correct_chars.peek() == Some(&c) {
                correct_chars.next();
            } else if c == HASANT {
                removed += 1;
            } else {
                return false;
            }
        }
        correct_chars.next().is_none() && removed > 0
    }

    #[test]
    fn common_words_are_corrected() {
        let words = [
            ("আম্রা", "আমরা"),
            ("এক্টা", "একটা"),
            ("আপ্নি", "আপনি"),
            ("বল্তে", "বলতে"),
            ("থাক্তে", "থাকতে"),
        ];
        for (engine, correct) in words {
            assert_eq!(lookup(engine), Some(correct), "{engine}");
        }
    }

    #[test]
    fn words_not_in_the_list_are_left_alone() {
        for word in ["ভক্ত", "শক্তি", "কিন্তু", "দেখতে", "আমরা", "", "আম্রাই"]
        {
            assert_eq!(lookup(word), None, "{word}");
        }
    }

    #[test]
    fn decomposed_nukta_letters_are_looked_up_precomposed() {
        let (engine, correct) = entries()
            .iter()
            .find(|e| e.engine.contains('\u{09DF}'))
            .map(|e| (e.engine, e.correct))
            .expect("the list has a word with U+09DF");
        let decomposed = engine.replace('\u{09DF}', "\u{09AF}\u{09BC}");
        assert_eq!(lookup(&decomposed), Some(correct));
    }

    #[test]
    fn words_in_text_are_corrected_and_everything_else_is_kept() {
        assert_eq!(
            correct_words("আম্রা এক্টা, ভক্ত১আপ্নি।\n\"থাক্তে\""),
            "আমরা একটা, ভক্ত১আপনি।\n\"থাকতে\""
        );
        assert_eq!(correct_words(""), "");
        assert_eq!(correct_words("  "), "  ");
    }

    #[test]
    fn the_list_is_sorted_with_one_entry_per_engine_spelling() {
        let entries = entries();
        assert!(entries.len() > 1000, "only {} entries", entries.len());
        for pair in entries.windows(2) {
            assert!(
                pair[0].engine < pair[1].engine,
                "{} is not before {}",
                pair[0].engine,
                pair[1].engine
            );
        }
        let lines = LIST.lines().filter(|l| !l.starts_with('#')).count();
        assert_eq!(lines, entries.len(), "every line is an entry");
    }

    #[test]
    fn the_list_has_no_decomposed_nukta_or_joiners() {
        for entry in entries() {
            for text in [entry.engine, entry.correct] {
                assert!(
                    !text.contains(['\u{09BC}', '\u{200C}', '\u{200D}']),
                    "{text}"
                );
            }
        }
    }

    /// Autocorrect spec, "Correction list": every entry matches the current
    /// engine (design D2). Fails on the first entry a rule change broke; run
    /// `scripts/autocorrect/generate.py` to regenerate the list.
    #[test]
    fn every_entry_matches_the_engine() {
        for entry in entries() {
            let Entry {
                engine,
                correct,
                roman,
            } = *entry;
            assert!(
                roman.contains('_'),
                "{engine}: no left-out vowel in {roman:?}"
            );
            assert!(
                only_hasants_removed(engine, correct),
                "{engine} → {correct}: not just hasants removed"
            );
            let typed = transpile_roman_document(&roman.replace('_', ""), false);
            assert_eq!(
                typed, engine,
                "{engine}: typing {roman:?} without the `_` no longer gives it; regenerate the list"
            );
            let restored = transpile_roman_document(&roman.replace('_', "o"), false);
            assert_eq!(
                restored, correct,
                "{engine}: typing {roman:?} with `o` at each `_` no longer gives {correct}; regenerate the list"
            );
        }
    }
}
